sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tK7Kk5vJMrod1mpf9Me
    access-key-secret: g8rNS1PIoWpCSgkBZ3bNVQYV0JJIXY
    bucket-name: vv-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx5f273eee9cfffa45
    secret: e45ba8f9947af4da779cbb8dd06174ca